/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.HoaDonController;
import dev.skyherobrine.app.controllers.dashboardui.thongKe.thongKeDoanhThuController;
//import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.HoaDonController;

import javax.swing.*;

/**
 *
 * @author Virtue Nguyen
 */
public class FormBaoCaoDoanhThuCuaHang extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public FormBaoCaoDoanhThuCuaHang() {
        initComponents();

        thongKeDoanhThuController controller = new thongKeDoanhThuController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
//     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBGThongTinCaNhan = new javax.swing.JPanel();
        pnBieuDoTHongKeDoanhThu = new javax.swing.JPanel();
        pnBoLocDoanhTHuCuaHang = new javax.swing.JPanel();
        pnKetQuaDoanhThu = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtBaoCaoDoanhThu = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBieuDoTHongKeDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        pnBieuDoTHongKeDoanhThu.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Biểu đồ thống kê doanh thu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        javax.swing.GroupLayout pnBieuDoTHongKeDoanhThuLayout = new javax.swing.GroupLayout(pnBieuDoTHongKeDoanhThu);
        pnBieuDoTHongKeDoanhThu.setLayout(pnBieuDoTHongKeDoanhThuLayout);
        pnBieuDoTHongKeDoanhThuLayout.setHorizontalGroup(
            pnBieuDoTHongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1186, Short.MAX_VALUE)
        );
        pnBieuDoTHongKeDoanhThuLayout.setVerticalGroup(
            pnBieuDoTHongKeDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnBoLocDoanhTHuCuaHang.setBackground(new java.awt.Color(255, 255, 255));
        pnBoLocDoanhTHuCuaHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bộ lọc doanh thu", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        javax.swing.GroupLayout pnBoLocDoanhTHuCuaHangLayout = new javax.swing.GroupLayout(pnBoLocDoanhTHuCuaHang);
        pnBoLocDoanhTHuCuaHang.setLayout(pnBoLocDoanhTHuCuaHangLayout);
        pnBoLocDoanhTHuCuaHangLayout.setHorizontalGroup(
            pnBoLocDoanhTHuCuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1641, Short.MAX_VALUE)
        );
        pnBoLocDoanhTHuCuaHangLayout.setVerticalGroup(
            pnBoLocDoanhTHuCuaHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        pnKetQuaDoanhThu.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kết quả thống kê");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Doanh thu:");

        txtBaoCaoDoanhThu.setText("Chua có dữ liệu");
        txtBaoCaoDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBaoCaoDoanhThuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnKetQuaDoanhThuLayout = new javax.swing.GroupLayout(pnKetQuaDoanhThu);
        pnKetQuaDoanhThu.setLayout(pnKetQuaDoanhThuLayout);
        pnKetQuaDoanhThuLayout.setHorizontalGroup(
            pnKetQuaDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addContainerGap(127, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(126, 126, 126))
            .addGroup(pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBaoCaoDoanhThu)
                .addGap(24, 24, 24))
        );
        pnKetQuaDoanhThuLayout.setVerticalGroup(
            pnKetQuaDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKetQuaDoanhThuLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnKetQuaDoanhThuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaoCaoDoanhThu))
                .addContainerGap(707, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBGThongTinCaNhanLayout = new javax.swing.GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBoLocDoanhTHuCuaHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnBieuDoTHongKeDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnKetQuaDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(pnBoLocDoanhTHuCuaHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnBieuDoTHongKeDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKetQuaDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBaoCaoDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBaoCaoDoanhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBaoCaoDoanhThuActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnBGThongTinCaNhan;
    private javax.swing.JPanel pnBieuDoTHongKeDoanhThu;
    private javax.swing.JPanel pnBoLocDoanhTHuCuaHang;
    private javax.swing.JPanel pnKetQuaDoanhThu;
    private javax.swing.JTextField txtBaoCaoDoanhThu;
    // End of variables declaration//GEN-END:variables
    public JPanel getPnBieuDoTHongKeDoanhThu() {
        return pnBieuDoTHongKeDoanhThu;
    }
    public JTextField getTxtBaoCaoDoanhThu() {
        return txtBaoCaoDoanhThu;
    }
}
