/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import dev.skyherobrine.app.controllers.dashboardui.mainDashboard.LapHoaDonController;
import dev.skyherobrine.app.views.dashboard.component.nutDuyetVaNutXoaDongTb.TableActionEvent1;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellEditor;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellRender;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionEvent;



import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.table.TableCellRenderer;


/**
 *
 * @author Virtue Nguyen
 */
public class LapHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public LapHoaDon() {
        initComponents();
        LapHoaDonController controller = new LapHoaDonController(this);
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellRenderer(new TableActionCellRender());
        tbDanhSachCacSanPhamTrongGioHang.getColumnModel().getColumn(7).setCellEditor(new TableActionCellEditor(controller));
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutDuyetVaNutXoaDongTb.TableActionCellEditor1(controller));
        tbHoaDonLuuTam.getColumnModel().getColumn(3).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutDuyetVaNutXoaDongTb.TableActionCellRender1());
        txtMaHoaDon.setEnabled(false);
        txtNgayLapHoaDon.setEnabled(false);
        txtGiamGia.setEnabled(false);
        txtTienDu.setEnabled(false);
        txtTienKhachDua.setEnabled(true);
        listProduct.addKeyListener(controller);
        listKhachHang.addKeyListener(controller);
        txtSoDienThoaiKh.addKeyListener(controller);
        txtTimKiemSanPham.addKeyListener(controller);
        menuProduct.add(panel2);
        menuKhachHang.add(pnTTKH);
        tbDanhSachCacSanPhamTrongGioHang.getModel().addTableModelListener(controller);
        btnLuuTam.addActionListener(controller);
        jCheckBox1.addActionListener(controller);
        txtTienKhachDua.addKeyListener(controller);
        btnLapHoaDon.addActionListener(controller);
        txtTimKiemHoaDonLuuTam.addKeyListener(controller);
        txtTienKhachDua.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProduct = new javax.swing.JList<>();
        menuProduct = new javax.swing.JPopupMenu();
        pnTTKH = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listKhachHang = new javax.swing.JList<>();
        menuKhachHang = new javax.swing.JPopupMenu();
        pnBGLapHoaDon = new javax.swing.JPanel();
        pnTraiLapHoaDon = new javax.swing.JPanel();
        pnPhaiTrenLapHoaDon = new javax.swing.JPanel();
        txtTimKiemSanPham = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        spDanhSachCacSanPhamTrongGioHang = new javax.swing.JScrollPane();
        tbDanhSachCacSanPhamTrongGioHang = new javax.swing.JTable();
        pnPhaiDuoiLapHoaDon = new javax.swing.JPanel();
        pnCamera = new javax.swing.JPanel();
        pnHoaDonLuuTam = new javax.swing.JPanel();
        spHoaDonLuuTam = new javax.swing.JScrollPane();
        tbHoaDonLuuTam = new javax.swing.JTable();
        txtTimKiemHoaDonLuuTam = new javax.swing.JTextField();
        pnPhaiLapHoaDon = new javax.swing.JPanel();
        pnThongTinHoaDon = new javax.swing.JPanel();
        pnThongTInKhachHang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTenKhachHang = new javax.swing.JTextField();
        txtSoDienThoaiKh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        pnThonhTinNhanVien = new javax.swing.JPanel();
        lbMaNhanVien = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtMaNhanVien = new javax.swing.JTextField();
        txtSoDienTHoaiNv = new javax.swing.JTextField();
        pnTHongTinHoaDon = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTienKhachDua = new javax.swing.JTextField();
        txtThue = new javax.swing.JTextField();
        txtTongTIen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayLapHoaDon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMaHoaDon = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTienDu = new javax.swing.JTextField();
        btnLapHoaDon = new javax.swing.JButton();
        btnLuuTam = new javax.swing.JButton();

        panel2.setPreferredSize(new java.awt.Dimension(390, 100));

        listProduct.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane1.setViewportView(listProduct);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuProduct.setFocusable(false);

        pnTTKH.setPreferredSize(new java.awt.Dimension(390, 100));

        listKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(listKhachHang);

        javax.swing.GroupLayout pnTTKHLayout = new javax.swing.GroupLayout(pnTTKH);
        pnTTKH.setLayout(pnTTKHLayout);
        pnTTKHLayout.setHorizontalGroup(
            pnTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnTTKHLayout.setVerticalGroup(
            pnTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuKhachHang.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnBGLapHoaDon.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnTraiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnPhaiTrenLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        txtTimKiemSanPham.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemSanPham.setText("");
        txtTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSanPhamActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách các sản phẩm trong giỏ hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        spDanhSachCacSanPhamTrongGioHang.setBackground(new java.awt.Color(255, 255, 255));

        tbDanhSachCacSanPhamTrongGioHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Số thứ tự", "Mã sản phẩm", "Tên sản phẩm", "Kích thước", "Số lượng", "Đơn giá", "Thành tiền", ""
            }
        ));
        tbDanhSachCacSanPhamTrongGioHang.setRowHeight(40);
        tbDanhSachCacSanPhamTrongGioHang.setSelectionBackground(new java.awt.Color(0, 255, 58));
        tbDanhSachCacSanPhamTrongGioHang.setSelectionForeground(new java.awt.Color(243, 7, 7));
        spDanhSachCacSanPhamTrongGioHang.setViewportView(tbDanhSachCacSanPhamTrongGioHang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachCacSanPhamTrongGioHang, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnPhaiTrenLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiTrenLapHoaDon);
        pnPhaiTrenLapHoaDon.setLayout(pnPhaiTrenLapHoaDonLayout);
        pnPhaiTrenLapHoaDonLayout.setHorizontalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                        .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnPhaiTrenLapHoaDonLayout.setVerticalGroup(
            pnPhaiTrenLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiTrenLapHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiDuoiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnCamera.setBackground(new java.awt.Color(255, 255, 255));
        pnCamera.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Camera", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        javax.swing.GroupLayout pnCameraLayout = new javax.swing.GroupLayout(pnCamera);
        pnCamera.setLayout(pnCameraLayout);
        pnCameraLayout.setHorizontalGroup(
            pnCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        pnCameraLayout.setVerticalGroup(
            pnCameraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnHoaDonLuuTam.setBackground(new java.awt.Color(255, 255, 255));
        pnHoaDonLuuTam.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hoá đơn lưu tạm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbHoaDonLuuTam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Số thứ tự", "Tên khách hàng", "Số điện thoại", ""
            }
        ));
        tbHoaDonLuuTam.setRowHeight(40);
        tbHoaDonLuuTam.setSelectionBackground(new java.awt.Color(0, 255, 91));
        tbHoaDonLuuTam.setSelectionForeground(new java.awt.Color(255, 0, 0));
        spHoaDonLuuTam.setViewportView(tbHoaDonLuuTam);

        javax.swing.GroupLayout pnHoaDonLuuTamLayout = new javax.swing.GroupLayout(pnHoaDonLuuTam);
        pnHoaDonLuuTam.setLayout(pnHoaDonLuuTamLayout);
        pnHoaDonLuuTamLayout.setHorizontalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
        );
        pnHoaDonLuuTamLayout.setVerticalGroup(
            pnHoaDonLuuTamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
        );

        txtTimKiemHoaDonLuuTam.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTimKiemHoaDonLuuTam.setText("");
        txtTimKiemHoaDonLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemHoaDonLuuTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnPhaiDuoiLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiDuoiLapHoaDon);
        pnPhaiDuoiLapHoaDon.setLayout(pnPhaiDuoiLapHoaDonLayout);
        pnPhaiDuoiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnCamera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTimKiemHoaDonLuuTam)
                    .addComponent(pnHoaDonLuuTam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnPhaiDuoiLapHoaDonLayout.setVerticalGroup(
            pnPhaiDuoiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiDuoiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnHoaDonLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiemHoaDonLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addComponent(pnCamera, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnTraiLapHoaDonLayout = new javax.swing.GroupLayout(pnTraiLapHoaDon);
        pnTraiLapHoaDon.setLayout(pnTraiLapHoaDonLayout);
        pnTraiLapHoaDonLayout.setHorizontalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnPhaiTrenLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiDuoiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnTraiLapHoaDonLayout.setVerticalGroup(
            pnTraiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTraiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnPhaiTrenLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiDuoiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnPhaiLapHoaDon.setBackground(new java.awt.Color(255, 255, 255));

        pnThongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        pnThongTInKhachHang.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTInKhachHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên khách hàng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");

        txtTenKhachHang.setEnabled(false);

        txtSoDienThoaiKh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiKhActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Khách vãng lai:");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jCheckBox1.setText("Tin chuẩn chưa");

        javax.swing.GroupLayout pnThongTInKhachHangLayout = new javax.swing.GroupLayout(pnThongTInKhachHang);
        pnThongTInKhachHang.setLayout(pnThongTInKhachHangLayout);
        pnThongTInKhachHangLayout.setHorizontalGroup(
            pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8))
                .addGap(21, 21, 21)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoDienThoaiKh)
                    .addComponent(txtTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                        .addComponent(jCheckBox1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnThongTInKhachHangLayout.setVerticalGroup(
            pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInKhachHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtTenKhachHang))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoaiKh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnThonhTinNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnThonhTinNhanVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin nhân viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        lbMaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaNhanVien.setText("Mã nhân viên:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Tên nhân viên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Số điện thoại:");

        txtTenNhanVien.setEnabled(false);

        txtMaNhanVien.setEnabled(false);

        txtSoDienTHoaiNv.setEnabled(false);

        javax.swing.GroupLayout pnThonhTinNhanVienLayout = new javax.swing.GroupLayout(pnThonhTinNhanVien);
        pnThonhTinNhanVien.setLayout(pnThonhTinNhanVienLayout);
        pnThonhTinNhanVienLayout.setHorizontalGroup(
            pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                        .addComponent(lbMaNhanVien)
                        .addGap(11, 11, 11)
                        .addComponent(txtMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                    .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                        .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9)))
                        .addGap(6, 6, 6)
                        .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenNhanVien)
                            .addComponent(txtSoDienTHoaiNv, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnThonhTinNhanVienLayout.setVerticalGroup(
            pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThonhTinNhanVienLayout.createSequentialGroup()
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaNhanVien))
                .addGap(18, 18, 18)
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenNhanVien)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnThonhTinNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtSoDienTHoaiNv)))
        );

        pnTHongTinHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnTHongTinHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Tiền khách đưa:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Thuế:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tổng tiền:");

        txtTienKhachDua.setEnabled(false);

        txtThue.setEnabled(false);

        txtTongTIen.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Ngày lập hoá đơn:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Mã hoá đơn:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Giảm giá:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Tiền dư:");

        javax.swing.GroupLayout pnTHongTinHoaDonLayout = new javax.swing.GroupLayout(pnTHongTinHoaDon);
        pnTHongTinHoaDon.setLayout(pnTHongTinHoaDonLayout);
        pnTHongTinHoaDonLayout.setHorizontalGroup(
            pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)
                        .addComponent(txtTienKhachDua))
                    .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75)
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiamGia, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtThue)))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNgayLapHoaDon)
                                    .addComponent(txtMaHoaDon)))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(75, 75, 75)
                                .addComponent(txtTongTIen, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTienDu, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnTHongTinHoaDonLayout.setVerticalGroup(
            pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTHongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtThue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTIen, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnTHongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTienDu)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLapHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLapHoaDon.setText("Lập hoá đơn");
        btnLapHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapHoaDonActionPerformed(evt);
            }
        });

        btnLuuTam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuuTam.setText("Lưu tạm hóa đơn");
        btnLuuTam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuTamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThongTinHoaDonLayout = new javax.swing.GroupLayout(pnThongTinHoaDon);
        pnThongTinHoaDon.setLayout(pnThongTinHoaDonLayout);
        pnThongTinHoaDonLayout.setHorizontalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThongTInKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnTHongTinHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnLapHoaDon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLuuTam)
                .addGap(37, 37, 37))
            .addGroup(pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnThonhTinNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnThongTinHoaDonLayout.setVerticalGroup(
            pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(pnThongTInKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTHongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuTam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pnThongTinHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnThongTinHoaDonLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(pnThonhTinNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(719, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnPhaiLapHoaDonLayout = new javax.swing.GroupLayout(pnPhaiLapHoaDon);
        pnPhaiLapHoaDon.setLayout(pnPhaiLapHoaDonLayout);
        pnPhaiLapHoaDonLayout.setHorizontalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        pnPhaiLapHoaDonLayout.setVerticalGroup(
            pnPhaiLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPhaiLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnThongTinHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnBGLapHoaDonLayout = new javax.swing.GroupLayout(pnBGLapHoaDon);
        pnBGLapHoaDon.setLayout(pnBGLapHoaDonLayout);
        pnBGLapHoaDonLayout.setHorizontalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGLapHoaDonLayout.createSequentialGroup()
                .addComponent(pnTraiLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnPhaiLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );
        pnBGLapHoaDonLayout.setVerticalGroup(
            pnBGLapHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnTraiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnPhaiLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGLapHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTimKiemHoaDonLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemHoaDonLuuTamActionPerformed
        if (txtTimKiemHoaDonLuuTam.getText().equalsIgnoreCase("Tìm kiếm hoá đơn lưu tạm")) {
        txtTimKiemHoaDonLuuTam.setText("");
        txtTimKiemHoaDonLuuTam.setForeground(Color.BLACK); // Đổi màu văn bản khi bắt đầu nhập
    }
    }//GEN-LAST:event_txtTimKiemHoaDonLuuTamActionPerformed

    private void txtTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSanPhamActionPerformed
        if(txtTimKiemSanPham.getText().equalsIgnoreCase("Tìm kiếm sản phẩm")){
            txtTimKiemSanPham.setText("");
            txtTimKiemSanPham.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_txtTimKiemSanPhamActionPerformed

    private void btnLapHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLapHoaDonActionPerformed
    }//GEN-LAST:event_btnLapHoaDonActionPerformed

    private void btnLuuTamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuTamActionPerformed
        // TODO add your handling code here:
//        System.out.println("Đã lưu bản nháp hoá đơm");
    }//GEN-LAST:event_btnLuuTamActionPerformed

    private void txtSoDienThoaiKhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKhActionPerformed

   public JTextField getTxtTimKiemSanPham(){
        return txtTimKiemSanPham;
    }
    public JTable getTbDanhSachCacSanPhamTrongGioHang(){
        return tbDanhSachCacSanPhamTrongGioHang;
    }
    public JTextField getTxtTimKiemHoaDonLuuTam(){
        return txtTimKiemHoaDonLuuTam;
    }
    public JPopupMenu getMenuKhachHang(){
        return menuKhachHang;
    }
    public JList getListKhachHang(){
        return listKhachHang;
    }
    public JTextField getTxtSoDienThoaiKh(){
        return txtSoDienThoaiKh;
    }
    public JPopupMenu getMenuProduct(){
        return menuProduct;
    }
    public JList getListProduct(){
        return listProduct;
    }
    public JPanel getPnCamera(){
        return pnCamera;
    }
    public JTextField getTxtTenNhanVien(){
        return txtTenNhanVien;
    }
    public JTextField getTxtMaNhanVien(){
        return txtMaNhanVien;
    }
    public JTextField getTxtSoDienTHoaiNv(){
        return txtSoDienTHoaiNv;
    }
    public JTextField getTxtTenKhachHang(){
        return txtTenKhachHang;
    }
    public JButton getBtnLapHoaDon(){
        return btnLapHoaDon;
    }
    public JButton getBtnLuuTam(){
        return btnLuuTam;
    }
    public JTextField getTxtMaHoaDon(){
        return txtMaHoaDon;
    }
    public JTextField getTxtNgayLapHoaDon(){
        return txtNgayLapHoaDon;
    }
    public JTextField getTxtThue(){
        return txtThue;
    }
    public JTextField getTxtGiamGia(){
        return txtGiamGia;
    }
    public JTextField getTxtTongTIen(){
        return txtTongTIen;
    }
    public JTextField getTxtTienKhachDua(){
        return txtTienKhachDua;
    }
    public JTextField getTxtTienDu(){
        return txtTienDu;
    }
    public JTable getTbHoaDonLuuTam(){
        return tbHoaDonLuuTam;
    }
    public JCheckBox getjCheckBox1(){
        return jCheckBox1;
    }
    public JTextField getTxtChietKhau(){
        return txtGiamGia;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLapHoaDon;
    private javax.swing.JButton btnLuuTam;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JList<String> listKhachHang;
    private javax.swing.JList<String> listProduct;
    private javax.swing.JPopupMenu menuKhachHang;
    private javax.swing.JPopupMenu menuProduct;
    private java.awt.Panel panel2;
    private javax.swing.JPanel pnBGLapHoaDon;
    private javax.swing.JPanel pnCamera;
    private javax.swing.JPanel pnHoaDonLuuTam;
    private javax.swing.JPanel pnPhaiDuoiLapHoaDon;
    private javax.swing.JPanel pnPhaiLapHoaDon;
    private javax.swing.JPanel pnPhaiTrenLapHoaDon;
    private javax.swing.JPanel pnTHongTinHoaDon;
    private java.awt.Panel pnTTKH;
    private javax.swing.JPanel pnThongTInKhachHang;
    private javax.swing.JPanel pnThongTinHoaDon;
    private javax.swing.JPanel pnThonhTinNhanVien;
    private javax.swing.JPanel pnTraiLapHoaDon;
    private javax.swing.JScrollPane spDanhSachCacSanPhamTrongGioHang;
    private javax.swing.JScrollPane spHoaDonLuuTam;
    private javax.swing.JTable tbDanhSachCacSanPhamTrongGioHang;
    private javax.swing.JTable tbHoaDonLuuTam;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaNhanVien;
    private javax.swing.JTextField txtNgayLapHoaDon;
    private javax.swing.JTextField txtSoDienTHoaiNv;
    private javax.swing.JTextField txtSoDienThoaiKh;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtThue;
    private javax.swing.JTextField txtTienDu;
    private javax.swing.JTextField txtTienKhachDua;
    private javax.swing.JTextField txtTimKiemHoaDonLuuTam;
    private javax.swing.JTextField txtTimKiemSanPham;
    private javax.swing.JTextField txtTongTIen;
    // End of variables declaration//GEN-END:variables
}
