/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
//import dev.skyherobrine.app.controllers.dashboardui.product.ProductController;
import dev.skyherobrine.app.controllers.dashboardui.product.ProductController;
import dev.skyherobrine.app.daos.product.SanPhamDAO;
import dev.skyherobrine.app.entities.order.PhieuNhapHang;
import dev.skyherobrine.app.controllers.dashboardui.product.ProductController;
import dev.skyherobrine.app.entities.product.SanPham;
import dev.skyherobrine.app.enums.MauSac;
import dev.skyherobrine.app.enums.PhongCachMac;
import dev.skyherobrine.app.enums.TinhTrangSanPham;
import dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionEvent;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import java.awt.*;
import java.util.List;


/**
 *
 * @author Virtue Nguyen
 */
public class QuanLySanPham extends javax.swing.JPanel {
    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLySanPham()  {
        initComponents();
        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onDelete(int row) {
                if(tbDIalogDanhSachCacSanPham.isEditing()){
                    tbDIalogDanhSachCacSanPham.getCellEditor().stopCellEditing();
                }
                DefaultTableModel defaultTableModel =  (DefaultTableModel) tbDIalogDanhSachCacSanPham.getModel();
                defaultTableModel.removeRow(row);
            }
        };
        ProductController controller = new ProductController(this);
        tbDIalogDanhSachCacSanPham.getColumnModel().getColumn(3).setCellRenderer(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellRender());
        tbDIalogDanhSachCacSanPham.getColumnModel().getColumn(3).setCellEditor(new dev.skyherobrine.app.views.dashboard.component.nutXoaDongTb.TableActionCellEditor(controller));
        tbDanhSachSanPham.addMouseListener(new ProductController(this));
        btnThemQuanLySanPham.addActionListener(new ProductController(this));
        btnSuaQuanLySanPham.addActionListener(new ProductController(this));
        btnXoaQuanLySanPham.addActionListener(new ProductController(this));
        cbTkDanhMuc.addActionListener(controller);
        cbTkLoaiSanPham.addActionListener(controller);
        cbTkTinhTrang.addActionListener(controller);
        cbTkTHuongHieu.addActionListener(controller);
        cbTkDoTuoi.addActionListener(controller);
        cbTkKieuNguoiMacSp.addActionListener(controller);
//
        txtTuKhoaTimKiem.addKeyListener(controller);
//        btnThemAnhSanPham.addActionListener(new ProductController(this));
        btnThemPBSP.addActionListener(controller);
        tbDanhSachSanPham.addMouseListener(controller);
        jDateChooserNgaySanXuat.setEnabled(false);
        cbDoTuoi.setEnabled(false);
        cbDanhMuc.setEnabled(false);
        cbKieuNguoiMac.setEnabled(false);
        cbLoaiSanPham.setEnabled(false);
        cbTh.setEnabled(false);
        cbTinhTrang.setEnabled(false);
        tbDIalogDanhSachCacSanPham.addMouseListener(controller);
        btnDialogThemXuong.addActionListener(controller);
        btnDialogAnh.addActionListener(controller);
        btnThemQuanLySanPham.addActionListener(controller);
        btnXoaQuanLySanPham.addActionListener(controller);
        btnSuaQuanLySanPham.addActionListener(controller);
        cbLoaiSanPham.addActionListener(controller);
        cbKieuNguoiMac.addActionListener(controller);
        tbDIalogDanhSachCacSanPham.getModel().addTableModelListener(controller);
        txtDialogMaSanPham.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        winThemPBSP = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtDialogMaSanPham = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbDialogKichThuoc = new javax.swing.JComboBox<>();
        cbDialogMauSac = new javax.swing.JComboBox<>();
        txtDialogSoLuong = new javax.swing.JTextField();
        pnDialogAnh = new javax.swing.JPanel();
        btnDialogAnh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        spDialogDanhSachPhienBanSanPham = new javax.swing.JScrollPane();
        tbDIalogDanhSachCacSanPham = new javax.swing.JTable();
        btnDialogXong = new javax.swing.JButton();
        btnDialogThemXuong = new javax.swing.JButton();
        pnBGThongTinCaNhan = new javax.swing.JPanel();
        pnThongTinSanPhamQuanLySanPham = new javax.swing.JPanel();
        lbMaSpQuanLySanPham = new javax.swing.JLabel();
        txtMaSpQuanLySanPham = new javax.swing.JTextField();
        lbMaLoaiSpQuanLySanPham = new javax.swing.JLabel();
        lbHhQuanLySanPham = new javax.swing.JLabel();
        lbTenSpQuanLySanPham = new javax.swing.JLabel();
        txtTenSpQuanLySanPham = new javax.swing.JTextField();
        lbNgaySanXuatQuanLySanPham = new javax.swing.JLabel();
        lbXuatXuQuanLySanPham = new javax.swing.JLabel();
        txtXuatXuQuanLySanPham = new javax.swing.JTextField();
        lbDoTuoiQuanLySanPham = new javax.swing.JLabel();
        txtPhanTramLoiQuanLySanPham = new javax.swing.JTextField();
        lbPhanTramLoiQuanLySanPham = new javax.swing.JLabel();
        lbPhongCachMguoiMacQuanLySanPham1 = new javax.swing.JLabel();
        btnSuaQuanLySanPham = new javax.swing.JButton();
        btnThemQuanLySanPham = new javax.swing.JButton();
        btnXoaQuanLySanPham = new javax.swing.JButton();
        cbLoaiSanPham = new javax.swing.JComboBox<>();
        cbTh = new javax.swing.JComboBox<>();
        cbKieuNguoiMac = new javax.swing.JComboBox<>();
        cbDoTuoi = new javax.swing.JComboBox<>();
        cbTinhTrang = new javax.swing.JComboBox<>();
        cbDanhMuc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserNgaySanXuat = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnThemPBSP = new javax.swing.JButton();
        PnDanhSachSanPhamQuanLySanPham = new javax.swing.JPanel();
        spDanhSachSapnPham = new javax.swing.JScrollPane();
        tbDanhSachSanPham = new javax.swing.JTable();
        pnTimKiemQuanLySanPham = new javax.swing.JPanel();
        cbTkKieuNguoiMacSp = new javax.swing.JComboBox<>();
        cbTkDanhMuc = new javax.swing.JComboBox<>();
        cbTkLoaiSanPham = new javax.swing.JComboBox<>();
        cbTkTinhTrang = new javax.swing.JComboBox<>();
        cbTkTHuongHieu = new javax.swing.JComboBox<>();
        cbTkDoTuoi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtTuKhoaTimKiem = new javax.swing.JTextField();

        winThemPBSP.setModal(true);
        winThemPBSP.setResizable(false);
        winThemPBSP.setSize(new java.awt.Dimension(660, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Mã sản phẩm:");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiên bản sản phẩm", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Màu sắc:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Kích thước:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số lượng:");

        cbDialogKichThuoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDialogKichThuoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbDialogKichThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDialogKichThuocActionPerformed(evt);
            }
        });

        cbDialogMauSac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDialogMauSac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtDialogSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout pnDialogAnhLayout = new javax.swing.GroupLayout(pnDialogAnh);
        pnDialogAnh.setLayout(pnDialogAnhLayout);
        pnDialogAnhLayout.setHorizontalGroup(
            pnDialogAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 152, Short.MAX_VALUE)
        );
        pnDialogAnhLayout.setVerticalGroup(
            pnDialogAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 182, Short.MAX_VALUE)
        );

        btnDialogAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDialogAnh.setText("Ảnh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnDialogAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnDialogAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(cbDialogMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbDialogKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDialogSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDialogMauSac, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDialogKichThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDialogSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnDialogAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDialogAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách phiên bản sản phẩm", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbDIalogDanhSachCacSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Màu sắc", "Kích thước", "Số lượng", ""
            }
        ));
        tbDIalogDanhSachCacSanPham.setRowHeight(40);
        spDialogDanhSachPhienBanSanPham.setViewportView(tbDIalogDanhSachCacSanPham);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDialogDanhSachPhienBanSanPham)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDialogDanhSachPhienBanSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
        );

        btnDialogXong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDialogXong.setText("Xong");

        btnDialogThemXuong.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDialogThemXuong.setText("Thêm xuống");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDialogThemXuong)
                .addGap(66, 66, 66))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDialogMaSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(btnDialogXong)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDialogMaSanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDialogThemXuong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDialogXong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout winThemPBSPLayout = new javax.swing.GroupLayout(winThemPBSP.getContentPane());
        winThemPBSP.getContentPane().setLayout(winThemPBSPLayout);
        winThemPBSPLayout.setHorizontalGroup(
            winThemPBSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winThemPBSPLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );
        winThemPBSPLayout.setVerticalGroup(
            winThemPBSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnThongTinSanPhamQuanLySanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTinSanPhamQuanLySanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin sản phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTinSanPhamQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbMaSpQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaSpQuanLySanPham.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMaSpQuanLySanPham.setText("Mã sản phẩm:");

        txtMaSpQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaSpQuanLySanPham.setEnabled(false);
        txtMaSpQuanLySanPham.setPreferredSize(new java.awt.Dimension(64, 25));

        lbMaLoaiSpQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaLoaiSpQuanLySanPham.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMaLoaiSpQuanLySanPham.setText("Loại sản phẩm:");

        lbHhQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbHhQuanLySanPham.setText("Thương hiệu:");

        lbTenSpQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTenSpQuanLySanPham.setText("Tên sản phẩm:");

        txtTenSpQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenSpQuanLySanPham.setEnabled(false);
        txtTenSpQuanLySanPham.setPreferredSize(new java.awt.Dimension(79, 33));

        lbNgaySanXuatQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgaySanXuatQuanLySanPham.setText("Ngày sản xuất:");

        lbXuatXuQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbXuatXuQuanLySanPham.setText("Xuất xứ:");

        txtXuatXuQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtXuatXuQuanLySanPham.setEnabled(false);

        lbDoTuoiQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbDoTuoiQuanLySanPham.setText("Độ tuổi:");

        txtPhanTramLoiQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtPhanTramLoiQuanLySanPham.setEnabled(false);

        lbPhanTramLoiQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPhanTramLoiQuanLySanPham.setText("Phần trăm lời:");

        lbPhongCachMguoiMacQuanLySanPham1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbPhongCachMguoiMacQuanLySanPham1.setText("Phong cách mặc:");

        btnSuaQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSuaQuanLySanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/edit.png"))); // NOI18N
        btnSuaQuanLySanPham.setText("Sửa sản phẩm");

        btnThemQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThemQuanLySanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/plus.png"))); // NOI18N
        btnThemQuanLySanPham.setText("Thêm sản phẩm");

        btnXoaQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaQuanLySanPham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/remove.png"))); // NOI18N
        btnXoaQuanLySanPham.setText("Xoá sản phẩm");

        cbLoaiSanPham.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbKieuNguoiMac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbKieuNguoiMac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDoTuoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDoTuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbTinhTrang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDanhMuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Tình trạng:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Danh mục:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phiên bản sản phẩm:");

        btnThemPBSP.setText("Thêm PBSP");

        javax.swing.GroupLayout pnThongTinSanPhamQuanLySanPhamLayout = new javax.swing.GroupLayout(pnThongTinSanPhamQuanLySanPham);
        pnThongTinSanPhamQuanLySanPham.setLayout(pnThongTinSanPhamQuanLySanPhamLayout);
        pnThongTinSanPhamQuanLySanPhamLayout.setHorizontalGroup(
            pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                                .addComponent(lbMaSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMaSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbNgaySanXuatQuanLySanPham)
                                    .addComponent(lbTenSpQuanLySanPham, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbDoTuoiQuanLySanPham, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbMaLoaiSpQuanLySanPham, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenSpQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbDoTuoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbTinhTrang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooserNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btnThemQuanLySanPham)))
                .addGap(234, 234, 234)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPhanTramLoiQuanLySanPham)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(lbPhongCachMguoiMacQuanLySanPham1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(lbXuatXuQuanLySanPham)
                            .addComponent(lbHhQuanLySanPham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtXuatXuQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbTh, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPhanTramLoiQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbKieuNguoiMac, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnThemPBSP))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addComponent(btnSuaQuanLySanPham)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaQuanLySanPham)
                        .addGap(279, 279, 279))))
        );
        pnThongTinSanPhamQuanLySanPhamLayout.setVerticalGroup(
            pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbHhQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXuatXuQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtXuatXuQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbNgaySanXuatQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNgaySanXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                        .addGap(21, 21, 21)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDoTuoiQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createSequentialGroup()
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbPhanTramLoiQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhanTramLoiQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPhongCachMguoiMacQuanLySanPham1)
                    .addComponent(cbKieuNguoiMac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbMaLoaiSpQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemPBSP))
                .addGap(54, 54, 54)
                .addGroup(pnThongTinSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnXoaQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(btnSuaQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        PnDanhSachSanPhamQuanLySanPham.setBackground(new java.awt.Color(255, 255, 255));
        PnDanhSachSanPhamQuanLySanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Sản Phẩm", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Danh mục", "Loại sản phẩm", "Phong cách", "Thương hiệu", "Độ  tuổi", "Tình trạng"
            }
        ));
        spDanhSachSapnPham.setViewportView(tbDanhSachSanPham);

        javax.swing.GroupLayout PnDanhSachSanPhamQuanLySanPhamLayout = new javax.swing.GroupLayout(PnDanhSachSanPhamQuanLySanPham);
        PnDanhSachSanPhamQuanLySanPham.setLayout(PnDanhSachSanPhamQuanLySanPhamLayout);
        PnDanhSachSanPhamQuanLySanPhamLayout.setHorizontalGroup(
            PnDanhSachSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSapnPham)
        );
        PnDanhSachSanPhamQuanLySanPhamLayout.setVerticalGroup(
            PnDanhSachSanPhamQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachSapnPham, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pnTimKiemQuanLySanPham.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemQuanLySanPham.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        cbTkKieuNguoiMacSp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkKieuNguoiMacSp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phong cách mặc", " ", " " }));

        cbTkDanhMuc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh mục", " " }));

        cbTkLoaiSanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkLoaiSanPham.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại sản phẩm", " " }));

        cbTkTinhTrang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkTinhTrang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tình trạng", " " }));

        cbTkTHuongHieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkTHuongHieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thương hiệu", " " }));

        cbTkDoTuoi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cbTkDoTuoi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Độ tuổi" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Từ khoá tìm kiếm");

        txtTuKhoaTimKiem.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout pnTimKiemQuanLySanPhamLayout = new javax.swing.GroupLayout(pnTimKiemQuanLySanPham);
        pnTimKiemQuanLySanPham.setLayout(pnTimKiemQuanLySanPhamLayout);
        pnTimKiemQuanLySanPhamLayout.setHorizontalGroup(
            pnTimKiemQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbTkDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkTHuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTkKieuNguoiMacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimKiemQuanLySanPhamLayout.setVerticalGroup(
            pnTimKiemQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnTimKiemQuanLySanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTkKieuNguoiMacSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkLoaiSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkTHuongHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbTkDoTuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnTimKiemQuanLySanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnBGThongTinCaNhanLayout = new javax.swing.GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnDanhSachSanPhamQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnThongTinSanPhamQuanLySanPham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiemQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addComponent(PnDanhSachSanPhamQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnTimKiemQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnThongTinSanPhamQuanLySanPham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbDialogKichThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDialogKichThuocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDialogKichThuocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnDanhSachSanPhamQuanLySanPham;
    private javax.swing.JButton btnDialogAnh;
    private javax.swing.JButton btnDialogThemXuong;
    private javax.swing.JButton btnDialogXong;
    private javax.swing.JButton btnSuaQuanLySanPham;
    private javax.swing.JButton btnThemPBSP;
    private javax.swing.JButton btnThemQuanLySanPham;
    private javax.swing.JButton btnXoaQuanLySanPham;
    private javax.swing.JComboBox<String> cbDanhMuc;
    private javax.swing.JComboBox<String> cbDialogKichThuoc;
    private javax.swing.JComboBox<String> cbDialogMauSac;
    private javax.swing.JComboBox<String> cbDoTuoi;
    private javax.swing.JComboBox<String> cbKieuNguoiMac;
    private javax.swing.JComboBox<String> cbLoaiSanPham;
    private javax.swing.JComboBox<String> cbTh;
    private javax.swing.JComboBox<String> cbTinhTrang;
    private javax.swing.JComboBox<String> cbTkDanhMuc;
    private javax.swing.JComboBox<String> cbTkDoTuoi;
    private javax.swing.JComboBox<String> cbTkKieuNguoiMacSp;
    private javax.swing.JComboBox<String> cbTkLoaiSanPham;
    private javax.swing.JComboBox<String> cbTkTHuongHieu;
    private javax.swing.JComboBox<String> cbTkTinhTrang;
    private com.toedter.calendar.JDateChooser jDateChooserNgaySanXuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbDoTuoiQuanLySanPham;
    private javax.swing.JLabel lbHhQuanLySanPham;
    private javax.swing.JLabel lbMaLoaiSpQuanLySanPham;
    private javax.swing.JLabel lbMaSpQuanLySanPham;
    private javax.swing.JLabel lbNgaySanXuatQuanLySanPham;
    private javax.swing.JLabel lbPhanTramLoiQuanLySanPham;
    private javax.swing.JLabel lbPhongCachMguoiMacQuanLySanPham1;
    private javax.swing.JLabel lbTenSpQuanLySanPham;
    private javax.swing.JLabel lbXuatXuQuanLySanPham;
    private javax.swing.JPanel pnBGThongTinCaNhan;
    private javax.swing.JPanel pnDialogAnh;
    private javax.swing.JPanel pnThongTinSanPhamQuanLySanPham;
    private javax.swing.JPanel pnTimKiemQuanLySanPham;
    private javax.swing.JScrollPane spDanhSachSapnPham;
    private javax.swing.JScrollPane spDialogDanhSachPhienBanSanPham;
    private javax.swing.JTable tbDIalogDanhSachCacSanPham;
    private javax.swing.JTable tbDanhSachSanPham;
    private javax.swing.JTextField txtDialogMaSanPham;
    private javax.swing.JTextField txtDialogSoLuong;
    private javax.swing.JTextField txtMaSpQuanLySanPham;
    private javax.swing.JTextField txtPhanTramLoiQuanLySanPham;
    private javax.swing.JTextField txtTenSpQuanLySanPham;
    private javax.swing.JTextField txtTuKhoaTimKiem;
    private javax.swing.JTextField txtXuatXuQuanLySanPham;
    private javax.swing.JDialog winThemPBSP;
    // End of variables declaration//GEN-END:variables
    public JDialog getWinThemPBSP(){return winThemPBSP;}
    public JTable getTbDanhSachSanPham(){
        return tbDanhSachSanPham;
    }
    public JTextField getTxtMaSanPham(){return txtMaSpQuanLySanPham;}
    public JTextField getTxtTenSanPham(){return txtTenSpQuanLySanPham;}
    public JDateChooser getJDateChooserNgaySanXuat(){return jDateChooserNgaySanXuat;}
    public JTextField getTxtXuatXu(){return txtXuatXuQuanLySanPham;}
    public JComboBox getCbDoTuoi(){return cbDoTuoi;}
    public JComboBox getCbTinhTrang(){return cbTinhTrang;}
    public JComboBox getDanhMuc(){return cbDanhMuc;}
    public JComboBox getCbLoai(){return cbLoaiSanPham;}
    public JComboBox getCbThuongHieu(){return cbTh;}
//    public JComboBox getCbMauSac(){return cbMauSac;}
//    public JTextField getTxtKichThuoc(){return txtKichThuocQuanLySanPham;}
    public JTextField getTxtPhamTramLoi(){return txtPhanTramLoiQuanLySanPham;}
    public JComboBox getCbKieuNguoiMac(){return cbKieuNguoiMac;}
//    public JPanel getPnImgSanPham(){return pnImgSanPham;}
    public JButton getButtonThem(){return btnThemQuanLySanPham;}
    public JButton getButtonSua(){return btnSuaQuanLySanPham;}
    public JButton getButtonXoa(){return btnXoaQuanLySanPham;}
//    public JTextField getTxtSoLuongSanPham(){return txtSoLuongSanPham;}
//    public JButton getBtnThemAnhSanPham(){return btnThemAnhSanPham;}
    public JTextField getTxtTuKhoaTimKiem(){return txtTuKhoaTimKiem;}
    public JComboBox getCbTkDanhMuc(){return  cbTkDanhMuc;}
    public JComboBox getCbTkLoaiSanPham(){return cbTkLoaiSanPham;}
    public JComboBox getCbTkTinhTrang(){return cbTkTinhTrang;}
    public JComboBox getCbTkThuongHieu(){return cbTkTHuongHieu;}
    public JComboBox getCbTkDoTuoi(){return cbTkDoTuoi;}
    public JComboBox getCbTkPhongCachMac(){return cbTkKieuNguoiMacSp;}
    public JButton getBtnThemPBSP(){return btnThemPBSP;}
    public JComboBox getCbDialogKichThuoc(){return cbDialogKichThuoc;}
    public JComboBox getCbDialogMauSac(){return cbDialogMauSac;}
    public JTable getTbDialogDanhSachCacSanPham(){return tbDIalogDanhSachCacSanPham;}
    public JPanel getPnDialogAnh(){return pnDialogAnh;}
    public JTextField getTxtDialogMaSanPham(){return txtDialogMaSanPham;}
    public JTextField getTxtDialogSoLuong(){return txtDialogSoLuong;}
    public JButton getBtnDialogAnh(){return btnDialogAnh;}
    public JButton getBtnDialogThemXuong(){return btnDialogThemXuong;}
    public JButton getBtnDialogXong(){return btnDialogXong;}

}
