/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package dev.skyherobrine.app.views.dashboard.component;

import com.toedter.calendar.JDateChooser;
import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.PhieuTraKHController;
//import dev.skyherobrine.app.controllers.dashboardui.QuanLyHoaDon.PhieuTraHangKHController;

import javax.swing.*;
import javax.swing.table.TableColumn;

/**
 *
 * @author Virtue Nguyen
 */
public class QuanLyPhieuTraHangChoKhachHang extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinCaNhan
     */
    public QuanLyPhieuTraHangChoKhachHang() {
        initComponents();
        PhieuTraKHController controller = new PhieuTraKHController(this);
        menuSuggestHD.add(pnSuggestHD);
        txtTimKiemHoaDon.addKeyListener(controller);
        listSuggestHD.addKeyListener(controller);
        tbDanhSachSanPhamTrongHoaDon.getModel().addTableModelListener(controller);
        txtMaHoaDon.setEnabled(false);
        txtNgayLapPhieu.setEnabled(false);
        txtGiamGia.setEnabled(false);
        txtTongTienHang.setEnabled(false);
        txtTongTienTraLai.setEnabled(false);
        jDateChooserNgayLapPhieu.setEnabled(false);
        jDateChooserTkTuNgay.addPropertyChangeListener("date", controller);
        jDateChooserTkDenNgay.addPropertyChangeListener("date", controller);
        btnTraHang.addActionListener(controller);
        txtTuKhoaTimKiem.addKeyListener(controller);
        jDateChooserTkDenNgay.setEnabled(false);
        tbDanhSachPhieuTraHangChoKhachHang.addMouseListener(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSuggestHD = new java.awt.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSuggestHD = new javax.swing.JList<>();
        menuSuggestHD = new javax.swing.JPopupMenu();
        pnBGThongTinCaNhan = new javax.swing.JPanel();
        pnThongTInPhieuTraHang = new javax.swing.JPanel();
        lbMaPhieuTra = new javax.swing.JLabel();
        txtMaPhieuTra = new javax.swing.JTextField();
        lbMaPhieuNhap = new javax.swing.JLabel();
        lbNgayLapPhieu = new javax.swing.JLabel();
        lbXuatXuQuanLySanPham = new javax.swing.JLabel();
        txtLyDoTraHang = new javax.swing.JTextField();
        txtMaPhieuNhap = new javax.swing.JTextField();
        jDateChooserNgayLapPhieu = new com.toedter.calendar.JDateChooser();
        pnDanhSachPhieuTraHang = new javax.swing.JPanel();
        spDanhSachPhieuTraHangChoKhachHang = new javax.swing.JScrollPane();
        tbDanhSachPhieuTraHangChoKhachHang = new javax.swing.JTable();
        pnTimKiemPhieuTraHang = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooserTkTuNgay = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserTkDenNgay = new com.toedter.calendar.JDateChooser();
        txtTuKhoaTimKiem = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pnDanhSachCacSanPhamTrongHoaDon = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDanhSachSanPhamTrongHoaDon = new javax.swing.JTable();
        txtTimKiemHoaDon = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayLapPhieu = new javax.swing.JTextField();
        txtMaHoaDon = new javax.swing.JTextField();
        txtGiamGia = new javax.swing.JTextField();
        txtTongTienHang = new javax.swing.JTextField();
        txtTongTienTraLai = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        btnTraHang = new javax.swing.JButton();

        pnSuggestHD.setPreferredSize(new java.awt.Dimension(347, 96));

        listSuggestHD.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listSuggestHD);

        javax.swing.GroupLayout pnSuggestHDLayout = new javax.swing.GroupLayout(pnSuggestHD);
        pnSuggestHD.setLayout(pnSuggestHDLayout);
        pnSuggestHDLayout.setHorizontalGroup(
            pnSuggestHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
        );
        pnSuggestHDLayout.setVerticalGroup(
            pnSuggestHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );

        menuSuggestHD.setFocusable(false);

        setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnBGThongTinCaNhan.setBackground(new java.awt.Color(255, 255, 255));
        pnBGThongTinCaNhan.setPreferredSize(new java.awt.Dimension(1651, 1000));

        pnThongTInPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnThongTInPhieuTraHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phiếu trả hàng của khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N
        pnThongTInPhieuTraHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lbMaPhieuTra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaPhieuTra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbMaPhieuTra.setText("Mã hoá đơn:");

        txtMaPhieuTra.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaPhieuTra.setEnabled(false);
        txtMaPhieuTra.setPreferredSize(new java.awt.Dimension(64, 25));

        lbMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbMaPhieuNhap.setText("Mã phiếu nhập:");

        lbNgayLapPhieu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbNgayLapPhieu.setText("Ngày lập phiếu:");

        lbXuatXuQuanLySanPham.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbXuatXuQuanLySanPham.setText("Lý do trả hàng:");

        txtLyDoTraHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLyDoTraHang.setEnabled(false);

        txtMaPhieuNhap.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaPhieuNhap.setEnabled(false);

        javax.swing.GroupLayout pnThongTInPhieuTraHangLayout = new javax.swing.GroupLayout(pnThongTInPhieuTraHang);
        pnThongTInPhieuTraHang.setLayout(pnThongTInPhieuTraHangLayout);
        pnThongTInPhieuTraHangLayout.setHorizontalGroup(
            pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongTInPhieuTraHangLayout.createSequentialGroup()
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbMaPhieuTra)
                            .addComponent(lbMaPhieuNhap))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNgayLapPhieu)
                            .addComponent(lbXuatXuQuanLySanPham))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMaPhieuTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLyDoTraHang)
                            .addComponent(txtMaPhieuNhap)
                            .addComponent(jDateChooserNgayLapPhieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        pnThongTInPhieuTraHangLayout.setVerticalGroup(
            pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongTInPhieuTraHangLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhieuTra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbMaPhieuNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserNgayLapPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNgayLapPhieu))
                .addGap(18, 18, 18)
                .addGroup(pnThongTInPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLyDoTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbXuatXuQuanLySanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnDanhSachPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachPhieuTraHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách phiếu trả hàng của khách hàng", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24))); // NOI18N

        tbDanhSachPhieuTraHangChoKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spDanhSachPhieuTraHangChoKhachHang.setViewportView(tbDanhSachPhieuTraHangChoKhachHang);

        javax.swing.GroupLayout pnDanhSachPhieuTraHangLayout = new javax.swing.GroupLayout(pnDanhSachPhieuTraHang);
        pnDanhSachPhieuTraHang.setLayout(pnDanhSachPhieuTraHangLayout);
        pnDanhSachPhieuTraHangLayout.setHorizontalGroup(
            pnDanhSachPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuTraHangChoKhachHang, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        pnDanhSachPhieuTraHangLayout.setVerticalGroup(
            pnDanhSachPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spDanhSachPhieuTraHangChoKhachHang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
        );

        pnTimKiemPhieuTraHang.setBackground(new java.awt.Color(255, 255, 255));
        pnTimKiemPhieuTraHang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm phiếu trả hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Từ ngày:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Đến ngày:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Từ khoá tìm kiếm:");

        javax.swing.GroupLayout pnTimKiemPhieuTraHangLayout = new javax.swing.GroupLayout(pnTimKiemPhieuTraHang);
        pnTimKiemPhieuTraHang.setLayout(pnTimKiemPhieuTraHangLayout);
        pnTimKiemPhieuTraHangLayout.setHorizontalGroup(
            pnTimKiemPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserTkDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnTimKiemPhieuTraHangLayout.setVerticalGroup(
            pnTimKiemPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnTimKiemPhieuTraHangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnTimKiemPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkTuNgay, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jDateChooserTkDenNgay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnTimKiemPhieuTraHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                        .addComponent(txtTuKhoaTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnDanhSachCacSanPhamTrongHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        pnDanhSachCacSanPhamTrongHoaDon.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách sản phẩm trong hoá đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tbDanhSachSanPhamTrongHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã sản phẩm", "Tên sản phẩm", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tbDanhSachSanPhamTrongHoaDon);

        javax.swing.GroupLayout pnDanhSachCacSanPhamTrongHoaDonLayout = new javax.swing.GroupLayout(pnDanhSachCacSanPhamTrongHoaDon);
        pnDanhSachCacSanPhamTrongHoaDon.setLayout(pnDanhSachCacSanPhamTrongHoaDonLayout);
        pnDanhSachCacSanPhamTrongHoaDonLayout.setHorizontalGroup(
            pnDanhSachCacSanPhamTrongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        pnDanhSachCacSanPhamTrongHoaDonLayout.setVerticalGroup(
            pnDanhSachCacSanPhamTrongHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDanhSachCacSanPhamTrongHoaDonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Phiếu trả hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mã hoá đơn:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Ngày lập phiếu:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Giảm giá:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Tổng tiền hàng:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Tổng tiền trả lại:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Ghi chú:");

        btnTraHang.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTraHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconButtonChungChoCacForm/icon-tra-hang.png"))); // NOI18N
        btnTraHang.setText("Trả hàng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNgayLapPhieu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGiamGia, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTongTienHang)
                            .addComponent(txtMaHoaDon)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtGhiChu)
                            .addComponent(txtTongTienTraLai))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(btnTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtMaHoaDon))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayLapPhieu)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiamGia)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienHang)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongTienTraLai)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtGhiChu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnBGThongTinCaNhanLayout = new javax.swing.GroupLayout(pnBGThongTinCaNhan);
        pnBGThongTinCaNhan.setLayout(pnBGThongTinCaNhanLayout);
        pnBGThongTinCaNhanLayout.setHorizontalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnDanhSachPhieuTraHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTimKiemPhieuTraHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnDanhSachCacSanPhamTrongHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnThongTInPhieuTraHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 37, Short.MAX_VALUE))
        );
        pnBGThongTinCaNhanLayout.setVerticalGroup(
            pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBGThongTinCaNhanLayout.createSequentialGroup()
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addComponent(pnDanhSachPhieuTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTimKiemPhieuTraHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnThongTInPhieuTraHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnBGThongTinCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtTimKiemHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pnDanhSachCacSanPhamTrongHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnBGThongTinCaNhanLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnBGThongTinCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public JTextField getTxtMaPhieuTra() {
        return txtMaPhieuTra;
    }
    public JDateChooser getjDateChooserTkNgayHenLay() {
        return jDateChooserTkDenNgay;
    }
    public JDateChooser getjDateChooserTkNgayLap() {
        return jDateChooserTkTuNgay;
    }
    public JTextField getTxtLyDoTraHang() {
        return txtLyDoTraHang;
    }
    public JTextField getTxtMaPhieuNhap() {
        return txtMaPhieuNhap;
    }
//    public JTextField getTxtSoLuongTra() {
//        return txtSoLuongTra;
//    }
    public JTextField getTxtTuKhoaTimKiem() {
        return txtTuKhoaTimKiem;
    }
//    public JTextField getTxtTinhTrang() {
//        return txtTinhTrang;
//    }
//    public JTextField getTxtTenNhaCungCapSanPham() {
//        return txtTenNhaCungCapSanPham;
//    }
//    public JTextField getTxtTenSanPham() {
//        return txtTenSanPham;
//    }
    public JDateChooser getjDateChooserNgayLapPhieu() {
        return jDateChooserNgayLapPhieu;
    }
    public JTable getTbDanhSachPhieuTraHangChoKhachHang() {
        return tbDanhSachPhieuTraHangChoKhachHang;
    }
    public JTable getTbDanhSachSanPhamTrongHoaDon() {
        return tbDanhSachSanPhamTrongHoaDon;
    }
    public JTextField getTxtGhiChu() {
        return txtGhiChu;
    }
    public JTextField getTxtGiamGia() {
        return txtGiamGia;
    }
    public JTextField getTxtMaHoaDon() {
        return txtMaHoaDon;
    }
    public JTextField getTxtNgayLapPhieu() {
        return txtNgayLapPhieu;
    }
    public JTextField getTxtTongTienHang() {
        return txtTongTienHang;
    }
    public JTextField getTxtTongTienTraLai() {
        return txtTongTienTraLai;
    }
    public JButton getBtnTraHang() {
        return btnTraHang;
    }
    public JTextField getTxtTimKiemHoaDon() {
        return txtTimKiemHoaDon;
    }
    public JList<String> getListSuggestHD() {
        return listSuggestHD;
    }
    public JPopupMenu getMenuSuggestHD() {
        return menuSuggestHD;
    }
    public JDateChooser getjDateChooserNgayLap(){
        return jDateChooserNgayLapPhieu;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTraHang;
    private com.toedter.calendar.JDateChooser jDateChooserNgayLapPhieu;
    private com.toedter.calendar.JDateChooser jDateChooserTkDenNgay;
    private com.toedter.calendar.JDateChooser jDateChooserTkTuNgay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbMaPhieuNhap;
    private javax.swing.JLabel lbMaPhieuTra;
    private javax.swing.JLabel lbNgayLapPhieu;
    private javax.swing.JLabel lbXuatXuQuanLySanPham;
    private javax.swing.JList<String> listSuggestHD;
    private javax.swing.JPopupMenu menuSuggestHD;
    private javax.swing.JPanel pnBGThongTinCaNhan;
    private javax.swing.JPanel pnDanhSachCacSanPhamTrongHoaDon;
    private javax.swing.JPanel pnDanhSachPhieuTraHang;
    private java.awt.Panel pnSuggestHD;
    private javax.swing.JPanel pnThongTInPhieuTraHang;
    private javax.swing.JPanel pnTimKiemPhieuTraHang;
    private javax.swing.JScrollPane spDanhSachPhieuTraHangChoKhachHang;
    private javax.swing.JTable tbDanhSachPhieuTraHangChoKhachHang;
    private javax.swing.JTable tbDanhSachSanPhamTrongHoaDon;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtLyDoTraHang;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtMaPhieuNhap;
    private javax.swing.JTextField txtMaPhieuTra;
    private javax.swing.JTextField txtNgayLapPhieu;
    private javax.swing.JTextField txtTimKiemHoaDon;
    private javax.swing.JTextField txtTongTienHang;
    private javax.swing.JTextField txtTongTienTraLai;
    private javax.swing.JTextField txtTuKhoaTimKiem;
    // End of variables declaration//GEN-END:variables
}
